In [1]:
import numpy as np
mat=np.linspace(1,16,16)
mat=mat.reshape(4,4)
mat=mat.transpose()
print(mat)
mat=mat.reshape(2,8)
print(mat)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]
[[ 1.  5.  9. 13.  2.  6. 10. 14.]
 [ 3.  7. 11. 15.  4.  8. 12. 16.]]
